config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("translates.urls", namespace="translate")),
]

translates/urls.py
from django.urls import path
from . import views

app_name = "translate"

urlpatterns = [
    path("", views.TranslateView.as_view(), name="home"),
    path("translate", views.TranslateAPIView.as_view(), name="translate"),
    path("login", views.LoginView.as_view(), name="login"),
    path("api", views.trans, name="api"),
]

translates/models.py
from django.db import models

# Create your models here.

translates/views.py
import requests , json, itertools
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

class TranslateView(TemplateView):
    
    template_name = "home.html"
    
class TranslateAPIView(TemplateView):
    
    template_name = "translation.html"
    
class LoginView(TemplateView):
    
    template_name = "login.html"
    
@csrf_exempt
def trans(request):
    try:
        data = json.loads(request.body)
        print(data)
        if data.get("source_lang") == "한국어":
            source_lang = 'ko'
            target_lang = 'en'
        else:
            source_lang = 'en'
            target_lang = 'ko'
        header = {"x-api-key":"a6007323cc1cffaa887dc6624f1d0a76","Content-Type":"application/json; charset=utf-8"}
        data_raw = {"q": f"{data.get('input')}","source_lang": f"{source_lang}","target_lang": f"{target_lang}",}
        request_post = requests.post(
            f"https://9b605f89-94d2-47a0-a61b-92547abb3017.api.kr-central-1.kakaoi.io/ai/translation/d6450e9fca05420abfad559feb086918",
            headers=header, data=json.dumps(data_raw)
        )
        result = request_post.json()
        print(result)
        output = result.get("output")
        text = ''
        for i in output:
            for j in i:
                text += j

        print(text)
        return JsonResponse({"output":text},status=200)
    except Exception as e:
        print(e)
        return JsonResponse({"messge":str(e)},status=500)

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="icon" href="" />
    <meta name="keywords" content="" />
    <meta name="description" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta property="og:locale" content="ko_KR">
    <meta property="og:site_name" content="">
    <meta property="og:type" content="website">
    <meta property="og:title" content="">
    <meta property="og:description" content="">
    <meta name="twitter:description" content="" />
    <meta name="twitter:image" content="" />
    <meta name="naver-site-verification" content="" />
    <meta name="facebook-domain-verification" content="" />

    <title>경이로움</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/layout.css' %}" type="text/css" /> 
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}" type="text/css" /> 
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    {% block static %}
    {% endblock static %}
  </head>
  <body>
    {% block content %} {% endblock content %}
    {% block js %}{% endblock js %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- 스킵 네비게이션 -->
<div class="skip_nav">
	<a href="#">'#' 바로가기</a>
	<a href="#">'#' 바로가기</a>
	<a href="#">'#' 바로가기</a>
</div>
<!-- 스킵 네비게이션 -->

<!-- 구분선 -->
<hr class="skip">
<!-- 구분선 -->

<!-- WRAP -->
<div id="wrap">

	<!-- HEADER -->
	<header id="header">
		
		<div class="header_wrap">

			<!-- 로고 -->
			<h1 class="logo">
				<a href="{% url 'translate:home' %}">경이로움 (로고 및 홈으로 이동)</a>
			</h1>
			<!-- 로고 -->

		</div>
		
	</header>
	<!-- HEADER -->
	
	<!-- 구분선 -->
	<hr class="skip">
	<!-- 구분선 -->

	<!-- MAIN -->
	<main role="main" id="container">
		<h2 class="skip">본문내용</h2>
		<section class="content">
			

			<section id="section01">
				<div class="inner">
					<div class="txt">
						<span>경이로움의 새로운 번역 서비스</span>
						<div>
							세상의 모든 책을 연결합니다. </br>책 만을 위한, <span>AI 기계번역</span> 솔루션입니다.
						</div>
						<a href="{% url 'translate:login' %}">지금 무료 체험하기</a>
					</div>
				</div>
			</section>
			<section id="section02" class="section">
				<div class="inner">
					<div class="txt">
						더 이상 고민되지 않은 가격으로 </br>1/10 가격이면 모든 번역이 가능합니다.
					</div>
					<div class="img">
						<img src="{% static 'assets/img/s02_01.svg' %}">
					</div>
					<a href="{% url 'translate:login' %}">지금 무료 체험하기</a>
				</div>
			</section>
			<section id="section03" class="section">
				<div class="inner">
					<div class="txt">
						시간을 절약하여 </br>더 많은 번역이 가능합니다.
					</div>
					<div class="img">
						<img src="{% static 'assets/img/s03_01.svg' %}">
					</div>
					<a href="{% url 'translate:login' %}">지금 무료 체험하기</a>
				</div>
			</section>
			<section id="section04" class="section">
				<div class="inner">
					<div class="txt">
						언제, 어디서든 </br>가장 <span>저렴한 비용</span>으로 가장 <span>빠르고 손 쉽게</span>
					</div>
					<div class="img">
						<img src="{% static 'assets/img/s04_01.svg' %}">
					</div>
				</div>
			</section>
			<section id="section05" class="section">
				<div class="inner">
					<div class="txt">
						지금 바로 번역 솔루션을 </br>가장 먼저 체험할 기회
						<small>1회 한정 무료체험 가능</small>
					</div>
					<a href="{% url 'translate:login' %}">지금 무료 체험하기</a>
				</div>
			</section>
			<section id="section06">
				<div class="inner">
					<div class="txt">
						실제 편집자의 </br>생생한 사용 후기
					</div>
					<ul>
						<li>
							<div class="subject">시간이 엄청 절약돼요!! 너무 좋아요</div>
							<div class="etc">
								<span>양**</span><span><img src="{% static 'assets/img/s06_01.svg' %}"></span>
							</div>
							<div class="content">
								솔직히 진짜 빨리 될까 싶었는데 진짜 엄청 빠르더라구요!  시간이 절약되니까 양도 늘릴 수 있고 너무 좋아요.
							</div>
						</li>
						<li>
							<div class="subject">번역에 어울리는 깔끔한 문체입니다.</div>
							<div class="etc">
								<span>김**</span><span><img src="{% static 'assets/img/s06_01.svg' %}"></span>
							</div>
							<div class="content">
								다른 번역 프로그램에 비해 어투가 자연스럽고 깔끔해 원서 번역에 많은 도움을 받았습니다.
							</div>
						</li>
						<li>
							<div class="subject">비용 절감이 기대됩니다! ^^</div>
							<div class="etc">
								<span>안**</span><span><img src="{% static 'assets/img/s06_01.svg' %}"></span>
							</div>
							<div class="content">
								경이로움 AI  기계번역을 통해 초안 번역을 완료하고,  검수를 의뢰하는 형식으로 비용 절감이 기대됩니다! ^^
							</div>
						</li>
						<li>
							<div class="subject">번역 원서를 선정하는데 도움이 돼요~~!</div>
							<div class="etc">
								<span>정**</span><span><img src="{% static 'assets/img/s06_01.svg' %}"></span>
							</div>
							<div class="content">
								모든 원서를 번역해보고 국내로 도입하기에 부담이 컸는데 무료 체험으로 질 좋은 번역을 체험해볼 수 있어서...
							</div>
						</li>
					</ul>
				</div>
			</section>
			<section id="section07">
				<div class="inner">
					<div class="txt">
						자주 묻는 질문
					</div>
				</div>
				<div class="list">
					<ul>
						<li class="menu">
							<a>
								<div class="q">다른 번역 프로그램과 차이가 있나요?</div>
							</a>
							<div style="">
								경이로움 AI  기계번역 솔루션은 모든 데이터를 활용하여 번역하는 타 플랫폼과 달리 책의 데이터와 문장 ,  문맥 등만을 활용하여 
								딥러닝 된 ‘책 번역 최적화’ 솔루션입니다.
							</div>
						</li>
						<li class="menu">
							<a>
								<div class="q">무료 체험은 어떻게 할 수 있나요?</div>
							</a>
							<div style="">
								베타테스트 기간에는 누구나 자유롭게 체험이 가능합니다.  실제 서비스 오픈 후에는 회원가입 및 로그인을 통해 5,000 byte 
								이내에서 체험이 가능합니다.  한 층 업그레이드 된 번역 솔루션의 결과물을 지금 바로 만나보세요.
							</div>
						</li>
						<li class="menu">
							<a>
								<div class="q">원서를 옮겨 적는 불편함 없이 스캔은 불가할까요?</div>
							</a>
							<div style="">
								경이로움 AI  기계번역 솔루션은 향후 1 회 당 번역량 확대,  스캔본 텍스트화,  번역 감수 전문가 연결 서비스 등 고객의 번역 편의를 
								위한 추가 시스템을 지속적으로 구축해나갈 계획입니다.
							</div>
						</li>
						<li class="menu">
							<a>
								<div class="q">제휴 문의</div>
							</a>
							<div style="">
								좋은 의견이 있으시다면 언제든지 (주)사이다경제(02-2088-5754, contact@cidermics.com) 로 연락주십시오.
							</div>
						</li>
					</ul>
				</div>
			</section>

		</section>
	</main>
	<!-- MAIN -->
	
	<!-- 구분선 -->
	<hr class="skip">
	<!-- 구분선 -->
	
	<!-- FOOTER -->
	<footer id="footer">
		<div class="f_wrap float">

			<div class="quick">
				<a href="{% url 'translate:login' %}">지금 무료 체험하기</a>
			</div>
			
			<div class="f_logo">
				<a href="{% url 'translate:home' %}">경이로움</a>
			</div>


			<div class="info float">
				<div class="fl">
					<div class="div01">(주) 사이다경제 Co., Ltd.</div>
					<div class="div02"><span>대표번호 02-2088-5754</span><span>운영시간 11-19시</span></div>
				</div>
				<div class="fr">
					<div class="div01"><span>대표 김의현</span><span>개인정보책임 김의현</span></div>
					<div class="div02"><span>사업자등록번호 586-81-00920</span><span>통신판매업 제2018-서울강남-03824호</span></div>
				</div>
			</div>
			<div class="f_menu">
				<ul>
					<li><a href="#">이용약관</a></li>
					<li><a href="#">개인정보처리방침</a></li>
				</ul>
			</div>
			<div class="copy">
				2022 사이다경제 CO., LTD ALL Rights Reserved.
			</div>
		</div>
	</footer>
	<!-- FOOTER -->

</div>
<!-- WRAP -->
{% endblock content %}
{% block js %}
<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script type="text/javascript">
	$(function(){
	 var rollHeader = 100;
	  $(window).scroll(function() {
		var scroll = getCurrentScroll();
		  if ( scroll >= rollHeader ) {
			   $('#header').addClass('roll');
			}
			else {
				$('#header').removeClass('roll');
			}
	  });
	function getCurrentScroll() {
		return window.pageYOffset || document.documentElement.scrollTop;
		}
	});
</script>
<script>
	$(".menu > a").click(function() {
		$(this).toggleClass('active').next('div').slideToggle(200);
		$(this).parent('.menu').toggleClass('active02');
		$(this).parent().siblings().children('div').slideUp(200);
		$(this).parent().siblings().children('.active').removeClass('active');
		$(this).parent('.active02').siblings().removeClass('active02');
		return false;
	});
</script>
<script type="text/javascript">

var prevScrollTop = 0;

var nowScrollTop = 0;

function wheelDelta(){
    return prevScrollTop - nowScrollTop > 0 ? 'up' : 'down';
};

$(window).on('scroll', function(){
nowScrollTop = $(this).scrollTop();
if(wheelDelta() == 'down'){
	$('.quick').addClass('roll');
}
if(wheelDelta() == 'up'){
	$('.quick').removeClass('roll');
}
prevScrollTop = nowScrollTop;
});

</script>
{% endblock js %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
	#header{background:#222;}
</style>

<body>

<!-- 스킵 네비게이션 -->
<div class="skip_nav">
	<a href="#">'#' 바로가기</a>
	<a href="#">'#' 바로가기</a>
	<a href="#">'#' 바로가기</a>
</div>
<!-- 스킵 네비게이션 -->

<!-- 구분선 -->
<hr class="skip">
<!-- 구분선 -->

<!-- WRAP -->
<div id="wrap">

	<!-- HEADER -->
	<header id="header">
		
		<div class="header_wrap">

			<!-- 로고 -->
			<h1 class="logo">
				<a href="{% url 'translate:home' %}">경이로움 (로고 및 홈으로 이동)</a>
			</h1>
			<!-- 로고 -->

		</div>
		
	</header>
	<!-- HEADER -->
	
	<!-- 구분선 -->
	<hr class="skip">
	<!-- 구분선 -->

	<!-- MAIN -->
	<main role="main" id="container">
		<h2 class="skip">본문내용</h2>
		<section class="content login">
			

			<section id="login_box">
				<h3>로그인</h3>
				<form method="POST" enctype="multipart/form-data">
					<div class="form mt30">
						<input type="text" name="" id="login_id" required="" class="ty01" maxlength="" placeholder="아이디">
					</div>
					<div class="form mt10">
						<input type="password" name="" id="login_pw" required="" class="ty01" maxlength="" placeholder="비밀번호">
					</div>
					<div class="ment mt10">아이디/비밀번호가 일치하지 않습니다.</div>
					<div class="form mt40 float">
						<div class="fl">
							<input type="checkbox" id="termsAgree" name="" class="" value="">
							<label for="termsAgree">자동 로그인</label>
						</div>
						<div class="fr">
							<a href="#" class="find">아이디/비밀번호 찾기</a>
						</div>
					</div>
					<div class="form mt20">
						<a href="{% url 'translate:translate' %}" class="btn_submit">로그인</a>
						{% comment %} <button type="submit" class="btn_submit">로그인</button> {% endcomment %}
						<a href="#" class="join_link mt10">회원가입</a>
					</div>
				</form>
			</section>


		</section>
	</main>
	<!-- MAIN -->
	
	<!-- 구분선 -->
	<hr class="skip">
	<!-- 구분선 -->
	
	<!-- FOOTER -->
	<footer id="footer">
		<div class="f_wrap float">
			
			<div class="f_logo">
				<a href="/">경이로움</a>
			</div>


			<div class="info float">
				<div class="fl">
					<div class="div01">(주) 사이다경제 Co., Ltd.</div>
					<div class="div02"><span>대표번호 02-2088-5754</span><span>운영시간 11-19시</span></div>
				</div>
				<div class="fr">
					<div class="div01"><span>대표 김의현</span><span>개인정보책임 김의현</span></div>
					<div class="div02"><span>사업자등록번호 586-81-00920</span><span>통신판매업 제2018-서울강남-03824호</span></div>
				</div>
			</div>
			<div class="f_menu">
				<ul>
					<li><a href="#">이용약관</a></li>
					<li><a href="#">개인정보처리방침</a></li>
				</ul>
			</div>
			<div class="copy">
				2022 사이다경제 CO., LTD ALL Rights Reserved.
			</div>
		</div>
	</footer>
	<!-- FOOTER -->

</div>
<!-- WRAP -->
{% endblock content %}
{% block js %}

<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script type="text/javascript">
	$(function(){
	 var rollHeader = 100;
	  $(window).scroll(function() {
		var scroll = getCurrentScroll();
		  if ( scroll >= rollHeader ) {
			   $('#header').addClass('roll');
			}
			else {
				$('#header').removeClass('roll');
			}
	  });
	function getCurrentScroll() {
		return window.pageYOffset || document.documentElement.scrollTop;
		}
	});
</script>
<script>
	$(".menu > a").click(function() {
		$(this).toggleClass('active').next('div').slideToggle(200);
		$(this).parent('.menu').toggleClass('active02');
		$(this).parent().siblings().children('div').slideUp(200);
		$(this).parent().siblings().children('.active').removeClass('active');
		$(this).parent('.active02').siblings().removeClass('active02');
		return false;
	});
</script>
<script type="text/javascript">

var prevScrollTop = 0;

var nowScrollTop = 0;

function wheelDelta(){
    return prevScrollTop - nowScrollTop > 0 ? 'up' : 'down';
};

$(window).on('scroll', function(){
nowScrollTop = $(this).scrollTop();
if(wheelDelta() == 'down'){
	$('.quick').addClass('roll');
}
if(wheelDelta() == 'up'){
	$('.quick').removeClass('roll');
}
prevScrollTop = nowScrollTop;
});

</script>
{% endblock js %}

templates/test.html
{% extends 'base.html' %}
{% load static i18n %}
{% block static %}
<link rel="stylesheet" href="{% static 'assets/main.css' %}" type="text/css" />
{% endblock static %}
{% block content %}

변역

<div class="a">
    <div class="b">
        <div id="source_lang">한국어</div>
        <button onclick="reverse()">바꾸기</button>
        <div id="target_lang">영어</div>
    </div>
    <div class="c">
        <textarea maxlength="5000" name="word" type="search" class="c_a"></textarea>
        <textarea  name="output" type="search" class="c_b"></textarea>
    </div>
</div>
<button onclick="api_test(event)">통신</button>
<input type="text" name="click">

{% endblock content %}


{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
<script>
    axios.defaults.xsrfCookieName = 'csrftoken'
    axios.defaults.xsrfHeaderName = "X-CSRFTOKEN"
    let data = {
        input : '',
        source_lang : '',
    }
    const source_lang = document.getElementById('source_lang')
    const target_lang = document.getElementById('target_lang')
    function api_test(event) {
        document.all.click.value ="클릭함"
        data.input = document.all.word.value
        data.source_lang = source_lang.innerText
        axios.post(`${origin}/api`,data).then((res)=> {
            document.all.output.value = res.data.output
        }).catch((err) => {
            console.log("err")
            document.all.click.value = `${err} 에러 ${origin}`
        })
    }
    function reverse() {
        if (source_lang.innerText === '한국어') {
            source_lang.innerText = '영어'
            target_lang.innerText = '한국어'
        } else {
            source_lang.innerText = '한국어'
            target_lang.innerText = '영어'
        }
    }
</script>
{% endblock js %}

templates/translation.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
#footer{padding:50px 0;}
</style>

<!-- 스킵 네비게이션 -->
<div class="skip_nav">
	<a href="#">'#' 바로가기</a>
	<a href="#">'#' 바로가기</a>
	<a href="#">'#' 바로가기</a>
</div>
<!-- 스킵 네비게이션 -->

<!-- 구분선 -->
<hr class="skip">
<!-- 구분선 -->

<!-- WRAP -->
<div id="wrap">

	<!-- HEADER -->
	<header id="header">
		
		<div class="header_wrap">

			<!-- 로고 -->
			<h1 class="logo">
				<a href="{% url 'translate:home' %}">경이로움 (로고 및 홈으로 이동)</a>
			</h1>
			<!-- 로고 -->

		</div>
		
	</header>
	<!-- HEADER -->
	
	<!-- 구분선 -->
	<hr class="skip">
	<!-- 구분선 -->

	<!-- MAIN -->
	<main role="main" id="container">
		<h2 class="skip">본문내용</h2>
		<section class="content translation">
			

			<section id="translation_box">
				<div class="change_btn"><a onclick="reverse()">바꾸기</a></div>
				<div class="ty01 fl">

					<select name="source_lang" id="ty01" required="">
						<option value="영어">영어</option>
					  	<option value="한국어">한국어</option>
					</select>

					<div class="before">
						<textarea placeholder="번역할 책 문단을 입력해주세요." name="word" maxlength="5000" id="textarea"></textarea>
						<span id="counter">###</span>
					</div>

					<div class="btn_wrap float">
						<div class="fl">
							<a id="before_copy">복사하기</a>
						</div>
						<div class="fr">
							<button onclick="api(event)">번역하기</button>
						</div>
					</div>
				</div>
				<div class="ty02 fl">

					<select name="target_lang" id="ty02" required="">
					  <option value="한국어">한국어</option>
					  <option value="영어">영어</option>
					</select>

					<div id="output" class="after">
					</div>
					<div class="btn_wrap float">
						<div class="fl">
							<a id='after_copy'>복사하기</a>
						</div>
					</div>
				</div>
			</section>

		</section>
	</main>
	<!-- MAIN -->
	
	<!-- 구분선 -->
	<hr class="skip">
	<!-- 구분선 -->
	
	<!-- FOOTER -->
	<footer id="footer">
		<div class="f_wrap float">
			
			<div class="f_logo">
				<a href="{% url 'translate:home' %}">경이로움</a>
			</div>


			<div class="info float">
				<div class="fl">
					<div class="div01">(주) 사이다경제 Co., Ltd.</div>
					<div class="div02"><span>대표번호 02-2088-5754</span><span>운영시간 11-19시</span></div>
				</div>
				<div class="fr">
					<div class="div01"><span>대표 김의현</span><span>개인정보책임 김의현</span></div>
					<div class="div02"><span>사업자등록번호 586-81-00920</span><span>통신판매업 제2018-서울강남-03824호</span></div>
				</div>
			</div>
			<div class="f_menu">
				<ul>
					<li><a href="#">이용약관</a></li>
					<li><a href="#">개인정보처리방침</a></li>
				</ul>
			</div>
			<div class="copy">
				2022 사이다경제 CO., LTD ALL Rights Reserved.
			</div>
		</div>
	</footer>
	<!-- FOOTER -->

</div>
<!-- WRAP -->
{% endblock content %}
{% block js %}

<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
<script>
    axios.defaults.xsrfCookieName = 'csrftoken'
    axios.defaults.xsrfHeaderName = "X-CSRFTOKEN"
    let data = {
        input : '',
        source_lang : '',
    }
    //const source_lang = document.getElementById('source_lang')
    //const target_lang = document.getElementById('target_lang')
	const output = document.getElementById('output')
	const source_lang = document.all.source_lang
	const target_lang = document.all.target_lang
    function api(event) {
        data.input = document.all.word.value
        data.source_lang = source_lang.value
        axios.post(`${origin}/api`,data).then((res)=> {
            output.innerText = res.data.output
        }).catch((err) => {
            console.log("err")
        })
    }
    function reverse() {
        let storage = source_lang.value
		source_lang.value = target_lang.value
		target_lang.value = storage
    }
	const before_copy = document.getElementById('before_copy')
	const after_copy = document.getElementById('after_copy')
	before_copy.addEventListener('click', () => {
		const dummy = document.createElement("textarea")
		document.body.appendChild(dummy)
		dummy.value = document.all.word.value
		dummy.select()
		document.execCommand('copy')
		document.body.removeChild(dummy)
		window.alert("복사되었습니다.")
		//navigator.clipboard.writeText(document.all.word.value).then((res) => {
		//	window.alert("클립보드에 복사되었습니다.")
		//})
		//document.all.word.select()
		//document.execCommand('copy')
	})
	after_copy.addEventListener('click', () => {
		const dummy = document.createElement("textarea")
		document.body.appendChild(dummy)
		dummy.value = output.innerText
		dummy.select()
		document.execCommand('copy')
		document.body.removeChild(dummy)
		window.alert("복사되었습니다.")
	})
</script>
<script type="text/javascript">
	$(function(){
	 var rollHeader = 100;
	  $(window).scroll(function() {
		var scroll = getCurrentScroll();
		  if ( scroll >= rollHeader ) {
			   $('#header').addClass('roll');
			}
			else {
				$('#header').removeClass('roll');
			}
	  });
	function getCurrentScroll() {
		return window.pageYOffset || document.documentElement.scrollTop;
		}
	});
</script>
<script>
	$(".menu > a").click(function() {
		$(this).toggleClass('active').next('div').slideToggle(200);
		$(this).parent().siblings().children('div').slideUp(200);
		$(this).parent().siblings().children('.active').removeClass('active');
		return false;
	});
</script>
<script type="text/javascript">

var prevScrollTop = 0;

var nowScrollTop = 0;

function wheelDelta(){
    return prevScrollTop - nowScrollTop > 0 ? 'up' : 'down';
};

$(window).on('scroll', function(){
nowScrollTop = $(this).scrollTop();
if(wheelDelta() == 'down'){
	$('.quick').addClass('roll');
}
if(wheelDelta() == 'up'){
	$('.quick').removeClass('roll');
}
prevScrollTop = nowScrollTop;
});

</script>
<script type="text/javascript">
$(function() {
      $('#textarea').keyup(function (e){
          var content = $(this).val();
          $(this).height(((content.split('\n').length + 1) * 1.5) + 'em');
          $('#counter').html(content.length + '<span>/5000</span>');
      });
      $('#textarea').keyup();
});
</script>
{% endblock js %}